In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import pacf, acf, pacf_burg
from statsmodels.regression.linear_model import yule_walker

In [3]:
df_sp = pd.read_csv('data/^GSPC.csv')
df_close = df_sp.set_index('Date')['Close']
df_close.index = pd.to_datetime(df_close.index)
time_series_preparation = TimeSeriesPreparation()
period_index_time_series = time_series_preparation.transform(df_close)
period_index_time_series.plot(figsize=(20, 5))
plt.show()

NameError: name 'TimeSeriesPreparation' is not defined

In [28]:
yule_walker(np.array([1, 2, 3, 4]), 3)

(array([ 1.05376344,  0.04516129, -0.27956989]), 1.1596563574540144)

In [61]:
pacf_burg(np.array([1, 2, 3, 4]), 3)

(array([ 1.        ,  0.45454545, -0.86153846, -1.        ]),
 array([1.25      , 0.72727273, 0.27692308, 0.        ]))

In [110]:
pacf(df_close, 10, method='ols-inefficient')

array([ 1.        ,  0.99678578,  0.21585029, -0.07415431, -0.14261948,
        0.0763923 , -0.02748249,  0.04997383, -0.17551864,  0.1915448 ,
       -0.16076186])

In [112]:
pacf(df_close, 10, method='yw')

array([ 1.        ,  0.99766614,  0.24265286, -0.05989888, -0.15223231,
        0.03884147, -0.01984205,  0.02960499, -0.14170889,  0.15407944,
       -0.09663423])

In [88]:
def autocorr(x, max_lags=None):
    n = len(x)
    if max_lags is None or max_lags > n:
        max_lags = n    
    x = (x - np.mean(x)) / (np.std(x) * np.sqrt(n))
    result = np.correlate(x, x, mode='full')[-n:-n + max_lags + 1]

    return result

autocorr(df_close.iloc[:15], max_lags=10)

array([ 1.        ,  0.58605525,  0.20859544, -0.06791727, -0.02257912,
       -0.12753209, -0.17429864, -0.31422696, -0.2072008 , -0.20595298,
       -0.13053124])

In [96]:
acf(df_close.iloc[:100], nlags=10)

array([ 1.        ,  0.74853224,  0.50835712,  0.39037324,  0.3113311 ,
        0.17684978,  0.0815524 , -0.03562858, -0.08027753, -0.11105834,
       -0.1508139 ])

In [94]:
acf(np.array([1, 1, 1, 1]), nlags=4)

array([nan, nan, nan, nan])

In [39]:
df_sp = pd.read_csv('data/^GSPC.csv')
df_close = df_sp.set_index('Date')['Close']

In [59]:
a, b = pacf(np.squeeze(df_close.values), alpha=0.05)

In [60]:
(b[3][1] - b[3][0])/2

0.05523765407649571