In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import pacf, acf, pacf_burg
from statsmodels.regression.linear_model import yule_walker

array([ 4, 11, 20, 30, 20, 11,  4])

In [28]:
yule_walker(np.array([1, 2, 3, 4]), 3)

(array([ 1.05376344,  0.04516129, -0.27956989]), 1.1596563574540144)

In [61]:
pacf_burg(np.array([1, 2, 3, 4]), 3)

(array([ 1.        ,  0.45454545, -0.86153846, -1.        ]),
 array([1.25      , 0.72727273, 0.27692308, 0.        ]))

In [70]:
pacf(np.array([1, 2, 3, 4]), 3, method='ols')

array([1.        , 1.        , 0.        , 0.26666667])

In [66]:
pacf(np.array([1, 2, 3, 4]), 3, method='ld')

array([ 1.        ,  0.33333333, -0.8       , -3.66666667])

In [12]:
acf(np.array([1, 2, 3, 4]), 4)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/statsmodels/tsa/stattools.py:541: FutureWarning: fft=True will become the default in a future version of statsmodels. To suppress this warning, explicitly set fft=False.
  warnings.warn(msg, FutureWarning)


array([ 1.        ,  0.33333333, -0.6       , -1.8       ])

In [39]:
df_sp = pd.read_csv('data/^GSPC.csv')
df_close = df_sp.set_index('Date')['Close']

In [59]:
a, b = pacf(np.squeeze(df_close.values), alpha=0.05)

In [60]:
(b[3][1] - b[3][0])/2

0.05523765407649571