In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import pacf, acf, pacf_burg
from statsmodels.regression.linear_model import yule_walker

In [3]:
df_sp = pd.read_csv('data/^GSPC.csv')
df_close = df_sp.set_index('Date')['Close']
df_close.index = pd.to_datetime(df_close.index)
time_series_preparation = TimeSeriesPreparation()
period_index_time_series = time_series_preparation.transform(df_close)
period_index_time_series.plot(figsize=(20, 5))
plt.show()

NameError: name 'TimeSeriesPreparation' is not defined

In [121]:
pacf(np.array([1, 2, 3, 4]), 3, method='ywm')

array([ 1.        ,  0.25      , -0.38666667, -0.31270903])

In [61]:
pacf_burg(np.array([1, 2, 3, 4]), 3)

(array([ 1.        ,  0.45454545, -0.86153846, -1.        ]),
 array([1.25      , 0.72727273, 0.27692308, 0.        ]))

In [110]:
pacf(df_close, 10, method='ols-inefficient')

array([ 1.        ,  0.99678578,  0.21585029, -0.07415431, -0.14261948,
        0.0763923 , -0.02748249,  0.04997383, -0.17551864,  0.1915448 ,
       -0.16076186])

In [123]:
df_close.iloc[:15]

Date
2015-03-18    2099.500000
2015-03-19    2089.270020
2015-03-20    2108.100098
2015-03-23    2104.419922
2015-03-24    2091.500000
2015-03-25    2061.050049
2015-03-26    2056.149902
2015-03-27    2061.020020
2015-03-30    2086.239990
2015-03-31    2067.889893
2015-04-01    2059.689941
2015-04-02    2066.959961
2015-04-06    2080.620117
2015-04-07    2076.330078
2015-04-08    2081.899902
Name: Close, dtype: float64

In [125]:
pacf(df_close.iloc[:15], 15, method='ywm')

array([ 1.        ,  0.58605525, -0.20541852, -0.15089993,  0.21536218,
       -0.30921943, -0.01974469, -0.20007992,  0.07772186, -0.19612716,
       -0.03519717,  0.13384736, -0.20629998,  0.00515652, -0.02735731,
       -0.0643404 ])

In [126]:
def autocorr(x, max_lags=None):
    n = len(x)
    if max_lags is None or max_lags > n:
        max_lags = n    
    x = (x - np.mean(x)) / (np.std(x) * np.sqrt(n))
    result = np.correlate(x, x, mode='full')[-n:-n + max_lags + 1]

    return result

autocorr(df_close.iloc[:15], max_lags=10)

array([ 1.        ,  0.58605525,  0.20859544, -0.06791727, -0.02257912,
       -0.12753209, -0.17429864, -0.31422696, -0.2072008 , -0.20595298,
       -0.13053124])

In [132]:
pacf(df_close.iloc[:15], nlags=15)

array([ 1.        ,  0.62791634, -0.25356867, -0.20313208,  0.33449225,
       -0.56728519,  0.04461552, -0.57387043,  0.56176693, -2.43215176,
       -1.11112319,  1.31361561,  3.46948907, -1.17651181, -0.37412882,
               nan])

In [96]:
acf(df_close.iloc[:100], nlags=10)

array([ 1.        ,  0.74853224,  0.50835712,  0.39037324,  0.3113311 ,
        0.17684978,  0.0815524 , -0.03562858, -0.08027753, -0.11105834,
       -0.1508139 ])

In [94]:
acf(np.array([1, 1, 1, 1]), nlags=4)

array([nan, nan, nan, nan])

In [39]:
df_sp = pd.read_csv('data/^GSPC.csv')
df_close = df_sp.set_index('Date')['Close']

In [59]:
a, b = pacf(np.squeeze(df_close.values), alpha=0.05)

In [60]:
(b[3][1] - b[3][0])/2

0.05523765407649571